openapi: 3.0.0
info:
  title: HydroGet
  description: Blah Blah
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/ashkans/hydroget/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://virtserver.swaggerhub.com/hydroget
  description: SwaggerHub API Auto Mocking
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers


paths:
  /rffe_info:
    get:
      operationId: rffe_info
      summary: An endpoint which returns a rar file incluidng data required for running a RORB hydrology model
      parameters:
      - name: latc
        in: query
        description: specfies the latitude of the catchment centriod
        required: false
        schema:
          type: number

      - name: lonc
        in: query
        description: specfies the longitude of the catchment centriod
        required: false
        schema:
          type: number

      - name: lato
        in: query
        description: specfies the latitude of the catchment outlet
        required: false
        schema:
          type: number          

      - name: lono
        in: query
        description: specfies the longitude of the catchment outlet
        required: false
        schema:
          type: number     

      - name: area
        in: query
        description: catchment area
        required: false
        schema:
          type: number 
          default: 88 

      - name: region
        in: query
        description: catchment region
        required: false
        schema:
          type: integer  
          default: 0

      - name: i2_6h
        in: query
        description: i2_6h
        required: false
        schema:
          type: number  
          default: 0     

      - name: i50_6h
        in: query
        description: 50% AEP 6 Hour Rainfall Intensity (mm/h)
        required: false
        schema:
          type: number  
          default: 0  
          
      - name: catchment_name
        in: query
        description: catchment name
        required: false
        schema:
          type: string  
          default: Catchment1               


      responses:
        '200':
          description: The requested data found and returned successfully.
          content:
            application/json:
              schema:
                type: string
                
      x-openapi-router-controller: swagger_server.controllers.io.get_data            
                




  /test/{name}.pdf:
    get:
      operationId: pdf
      summary: Returns the report in the PDF format
      parameters:
      - name: name
        in: path
        description: the name of the required file
        required: true
        schema:
          type: string
        
      responses:
        '200':
          description: A PDF file
          content:
            application/pdf:
              schema:
                type: string
                format: binary
      x-openapi-router-controller: swagger_server.controllers.examples.files
  
  /test/get_file/{name}:
    get:
      operationId: octet
      summary: Returns a generic file
      parameters:
      - name: name
        in: path
        description: the name of the required file
        required: true
        schema:
          type: string
        
      responses:
        '200':
          description: A generic file
          headers:
            Content-Disposition:
              schema:
                type: string
              description: the format is `attachment; filename="name.zip"`          
          content:
            application/vnd.rar:
              schema:
                type: string
                format: binary

      x-openapi-router-controller: swagger_server.controllers.examples.files      


components:
  schemas:
    Coordinates:
      type: number
      example: 
